// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Model;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Лоран Гунель",
                            CategoryId = 2,
                            Description = "Книга \"Бог всегда путешествует инкогнито\" Лорана Гунеля, входящего в пятерку самых популярных беллетристов Франции, стала всемирным бестселлером, несколько лет возглавляла топ-листы продаж во Франции и была переведена на множество языков.Представьте себе: вы на краю пропасти. И в этот судьбоносный момент некий человек спасает вашу жизнь. Взамен вы даете ему обязательство следовать всем его указаниям. Это должно изменить вашу жизнь, сделав ее более радостной и счастливой. Это больше, чем роман, это размышление о себе, которое должно побудить вас взять судьбу в собственные руки.",
                            ImageUrl = "https://s2-goods.ozstatic.by/2000/592/756/10/10756592_0.jpg",
                            Price = 17.0,
                            Title = "Бог всегда путешествует инкогнито"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Мосян Тунсю",
                            CategoryId = 4,
                            Description = "В незапамятные времена Се Лянь был наследным принцем государства Сяньлэ. Судьба одарила его всем: прекрасным ликом, чистыми помыслами и бесконечной любовью своих подданных. И если уж кому-то и было предначертано стать Божеством, то именно Его Высочеству.",
                            ImageUrl = "https://s4-goods.ozstatic.by/2000/97/93/101/101093097_0.jpg",
                            Price = 34.0,
                            Title = "Благословение небожителей. Том 1"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Николас Спаркс",
                            CategoryId = 2,
                            Description = "Это – не \"любовный роман\", а роман о любви. О любви обычных мужчины и женщины – таких как мы.\r\n\r\nПочему же книга эта стала абсолютным бестселлером в США? Почему она трогает душу читателей самого разного возраста и интеллектуального уровня? Объяснить это невозможно.\r\n\r\nПрочитайте \"Дневник памяти\" – и поймете сами!",
                            ImageUrl = "https://s3-goods.ozstatic.by/2000/94/60/1/1060094_0.jpg",
                            Price = 11.0,
                            Title = "Дневник памяти"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Артур Хейли",
                            CategoryId = 6,
                            Description = "Вечеринка \"золотой молодёжи\" закончилась большой бедой...\r\n\r\nТитулованный иностранец случайно совершил преступление – и ищет возможность уйти от ответа...\r\n\r\nДочь миллионера, спасённая из рук насильников, влюбляется в своего спасителя...\r\n\r\nНет, это не детектив. Это – просто повседневная жизнь гигантского, роскошного отеля. Здесь делаются карьеры. Здесь разбиваются сердца. Здесь совершаются сделки и зарабатываются деньги.\r\n\r\nЗдесь просто живут...",
                            ImageUrl = "https://s3-goods.ozstatic.by/2000/344/38/1/1038344_0.jpg",
                            Price = 15.0,
                            Title = "Отель"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Колин Маккалоу",
                            CategoryId = 2,
                            Description = "Любовный роман, поднятый на уровень настоящей литературы. Трогательная история взаимоотношений влюбленных, завораживающая читателя своей искренностью, чистотой и глубиной...",
                            ImageUrl = "https://s1-goods.ozstatic.by/2000/100/141/10/10141100_0.jpg",
                            Price = 14.0,
                            Title = "Поющие в терновнике"
                        });
                });

            modelBuilder.Entity("webapi.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Детективы"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Романы"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Приключения"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Романтика"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Юмор"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ужасы"
                        });
                });

            modelBuilder.Entity("webapi.Model.Book", b =>
                {
                    b.HasOne("webapi.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
